# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "企业版打包"
  before_all do |lane, options|
     puts "before_all"
  end

  before_each do |lane, options|
     puts "before_each"
  end

  lane :inHouse do |options|
  update_app_identifier(
    app_identifier: "com.dawoo.gamebox.sid#{options[:sid]}",
    plist_path: "./#{options[:scheme]}/Info.plist"
  )
  update_info_plist(
    display_name: options[:app_name],
    plist_path: "./#{options[:scheme]}/Info.plist"
  )
  gym(scheme: "#{options[:scheme]}",
      clean: true,
      workspace: "#{options[:scheme]}.xcworkspace",
      configuration: "Release",
      xcargs: "-allowProvisioningUpdates",
      export_method: "enterprise",
      output_directory: "#{options[:uplevel_path]}/pkgs/#{options[:code]}",
      output_name: "app_#{options[:code]}_#{options[:version]}"
   )
   after_all do |lane, options|
     puts ">>>打包完毕 删除app.dSYM.zip文件"
     sh("rm -f #{options[:uplevel_path]}/pkgs/#{options[:code]}/app_#{options[:code]}_#{options[:version]}.app.dSYM.zip")
   end

   error do |lane, exception, options|
      #puts ">>>>>err"
   end

  end
end
